In [1]:
import numpy as np
import cv2
import face_recognition as fr
import os
from datetime import datetime

In [2]:
path = "images"
images = []
img_names = []

mylist = os.listdir(path) 

for img in mylist:
    cur_img = cv2.imread(f'{path}/{img}')
    images.append(cur_img)
    img_names.append(os.path.splitext(img)[0])

In [3]:
def find_encoding(images):
    encode_list = []
    for img in images:
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        img_encode = fr.face_encodings(img)[0]
        encode_list.append(img_encode)
    return encode_list  

In [4]:
encoded_images = find_encoding(images)
len(encoded_images)

6

In [5]:
def mark_attendance(name):
    with open('Attendance.csv', 'r+') as f:
        my_data_list = f.readlines()
        name_list = []
        for line in my_data_list:
            entry = line.split(',')
            name_list.append(entry[0])
        if name not in name_list:
            now = datetime.now()
            dt_string = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dt_string}')

In [6]:
cap = cv2.VideoCapture(0)

In [ ]:
while True:
    success, img = cap.read()
    img_compress = cv2.resize(img, (0,0), None, 0.25, 0.25)
    img_compress = cv2.cvtColor(img_compress,cv2.COLOR_BGR2RGB)
    faces_cur_frame = fr.face_locations(img_compress)
    encodes_cur_frame = fr.face_encodings(img_compress, faces_cur_frame)
    
    for encode_face, face_loc in zip(encodes_cur_frame, faces_cur_frame):
        matches = fr.compare_faces(encoded_images, encode_face)
        face_dist = fr.face_distance(encoded_images, encode_face)
        print(face_dist)
        match_index = np.argmin(face_dist)
        
        if matches[match_index]:
            name = img_names[match_index].upper()
            print(name)
            y1, x2, y2, x1 = face_loc
            y1, x2, y2, x1 = 4*y1, 4*x2, 4*y2, 4*x1
            cv2.rectangle(img, (x1, y1), (x2, y2), (0,0,255), 2)
            cv2.rectangle(img, (x1, y2-35), (x2, y2), (0,0,255), cv2.FILLED)
            cv2.putText(img, name, (x1+6, y2-6), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 2)
            mark_attendance(name)

            
    cv2.imshow("webcam", img)
    cv2.waitKey(1)

[0.77226462 0.76552339 0.65683368 0.68447643 0.50262979 0.81758465]
OMAR
[0.84567738 0.83972796 0.71127667 0.63780003 0.39376053 0.82415434]
OMAR
[0.84398601 0.84379953 0.7266908  0.65411437 0.4350076  0.83589697]
OMAR
[0.86231696 0.85961044 0.73469391 0.63737506 0.40291802 0.84510696]
OMAR
[0.82387693 0.80955308 0.72571516 0.65116063 0.42041964 0.85263407]
OMAR
[0.823651   0.82495388 0.67873929 0.63494038 0.43688984 0.78980169]
OMAR
[0.81320369 0.81016417 0.6702284  0.52132618 0.56283573 0.78869574]
OMAR AZIZ
[0.90706699 0.9161485  0.74769725 0.439455   0.56502089 0.83683227]
OMAR AZIZ
[0.9358074  0.93876437 0.76398103 0.45664279 0.59126976 0.85958972]
OMAR AZIZ
[0.96821094 0.98208522 0.78492088 0.48550519 0.58735707 0.84456665]
OMAR AZIZ
[0.92423757 0.93595334 0.75464578 0.45443183 0.61141629 0.84165703]
OMAR AZIZ
[0.9282401  0.92787599 0.73175335 0.42727152 0.61934293 0.83911629]
OMAR AZIZ
[0.89329978 0.90039519 0.75713228 0.43648526 0.58206957 0.8112407 ]
OMAR AZIZ
[0.93891341 0.91